language: php

services:
  - docker

env:
  - IMAGE_NAME=einarvalur/althingi-store-db

script:
    - echo "althingi-store-db"

before_deploy:
  - docker build --build-arg ENV=production -t "$IMAGE_NAME" .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - git_sha="$(git rev-parse --short HEAD)"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${git_sha}"

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${git_sha}"
  on:
    branch: main
